---
title       : x2VOL Claims Mapping
subtitle    : Geographic distribution of students in the x2VOL volunteer tracking system
author      : Eric Byrnes
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
logo        : logo.png
knit        : slidify::knit2slides

--- .class #page_2
<style type="text/css">
strong {
   font-weight: bold;
}

.title-slide {
   background-color: white;
}
</style>

## x2VOL Introduction

- Data is drawn from [x2VOL volunteer tracking system](http://www.x2vol.com)
   - Consists of **volunteer claims**
   - A **claim** consists of a volunteer reporting time spent at a single volunteering activity on a single day
- Population is primarily high school students (some in middle school)
- Students perform volunteering/community service
   - Schools recognize this: toward graduation requirements, as college preparation, as component of service learning
- Approximately 375 schools, 150,000 students (primarily in US and Canada)
- Data is weighted toward later years due to company/system growth

--- .class #page_3
## Application

- Displays map of US volunteers
   - Darker shades indicate relative number of volunteers
   - Size of bubbles indicate relative number of hours claimed, verified, or approved
- Hover over bubble clusters to magnify them
- Hover over individual bubbles to see location and claim summary details
- Map may take a short time to reload after changing parameters!

--- .class #page_4
## Application Parameters

- **Since Year** - Slider sets the starting date (year) for data retrieval
   - If "2012" is set, volunteering claims on or after Jan 1, 2012 are reported
   - Year 2013 and later contain greatest concentration of reported claims
- **Claim Level** - Dropdown
   - Each claim contains **claimed hours** reported by the volunteer
   - Claim includes **verified hours** - the hours a third-party reported for the volunteer's claim
   - Claim includes **approved hours** - the hours the volunteer's school approved toward graduation, extracurricular goals, or other school-sponsored volunteering or service learning requirements
   - Verified hours and Approved hours may differ from claimed hours!

--- .class #page_5
## Application Demo

- Querying for
   - **Since Year** - 2014 - January 1, 2014 and later data
   - **Claim Level** - Claimed Hours
- Shows the following interactive map

```{r mapdemo, opts.label = 'interactive', echo = FALSE, results = 'asis'}
suppressPackageStartupMessages(require(googleVis))
suppressPackageStartupMessages(require(dplyr))

# static data
#  help text for claim level selection
claimHelp <- c(
   "C" = "Number of volunteering hours claimed by volunteers",
   "V" = "Number of volunteering hours verified by a third party",
   "A" = "Number of volunteering hours approved by schools toward graduation or other formal service learning requirement")
#  field name
claimField <- c(
   "C" = "Claimed Hours",
   "V" = "Verified Hours",
   "A" = "Approved Hours")

claims <- read.csv("./Claims.csv",
                   colClasses = c("Date",
                                  rep("numeric", 3),
                                  rep("integer", 2),
                                  "character",
                                  rep("numeric", 2),
                                  "character",
                                  "character"),
                   stringsAsFactors = FALSE)
#  fix up unverified / unapproved claims
claims[is.na(claims$VerifiedHrs), "VerifiedHrs"] <- 0
claims[is.na(claims$ApprovedHrs), "ApprovedHrs"] <- 0
# zip code latitude/longitude lookup
zips <- read.csv("./ClaimZips.csv",
                 colClasses = c("character",
                                rep("numeric", 2),
                                "character",
                                "character"),
                 stringsAsFactors = FALSE)
zips[, "ZipDesc"] <- paste0("Zip Code ", zips[, "Zip"],
                            " (", zips[, "StateCode"], ")")

#  filter data according to inputs
claims.filter <- claims %>%
   filter(WorkMonth >= as.Date("2014-01-01")) %>%
   group_by(Zip) %>%
   summarise(ClaimedHrs = sum(ClaimedHrs),
             VerifiedHrs = sum(VerifiedHrs),
             ApprovedHrs = sum(ApprovedHrs),
             NumClaims = sum(NumClaims),
             NumVolunteers = sum(NumVolunteers))

#  column names
names(claims.filter)[2:4] <- claimField
names(claims.filter)[5:6] <- c("Number of Claims", "Number of Volunteers")

#  merge with zip code data
claims.map <- merge(claims.filter, zips, by = "Zip")

c <- gvisGeoChart(claims.map,
   locationvar = "LatLong",
   colorvar = "Number of Volunteers",
   sizevar = "Claimed Hours",
   hovervar = "ZipDesc",
   options = list(region = "US", displayMode = "markers",
                  width = 550, height = 370,
                  colorAxis = "{ colors: ['#b3ff99','#00ff00'] }",
                  backgroundColor = "#dfffff")
)
print(c, "chart")
```
